# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T03:07:35+00:00

from __future__ import annotations

from enum import Enum
from typing import Dict, List, Optional

from pydantic import BaseModel, Field, RootModel


class Axis(BaseModel):
    end: Optional[float] = Field(None, description='maximum value')
    start: Optional[float] = Field(None, description='minimum value')
    tag: Optional[str] = Field(None, description='tag name.')


class Webfont(BaseModel):
    axes: Optional[List[Axis]] = Field(None, description='Axis for variable fonts.')
    category: Optional[str] = Field(None, description='The category of the font.')
    family: Optional[str] = Field(None, description='The name of the font.')
    files: Optional[Dict[str, str]] = Field(
        None,
        description='The font files (with all supported scripts) for each one of the available variants, as a key : value map.',
    )
    kind: Optional[str] = Field(
        None,
        description='This kind represents a webfont object in the webfonts service.',
    )
    lastModified: Optional[str] = Field(
        None,
        description='The date (format "yyyy-MM-dd") the font was modified for the last time.',
    )
    menu: Optional[str] = Field(
        None,
        description='Font URL for menu subset, a subset of the font that is enough to display the font name',
    )
    subsets: Optional[List[str]] = Field(
        None, description='The scripts supported by the font.'
    )
    variants: Optional[List[str]] = Field(
        None, description='The available variants for the font.'
    )
    version: Optional[str] = Field(None, description='The font version.')


class WebfontList(BaseModel):
    items: Optional[List[Webfont]] = Field(
        None, description='The list of fonts currently served by the Google Fonts API.'
    )
    kind: Optional[str] = Field(
        None,
        description='This kind represents a list of webfont objects in the webfonts service.',
    )


class CapabilityEnum(Enum):
    CAPABILITY_UNSPECIFIED = 'CAPABILITY_UNSPECIFIED'
    WOFF2 = 'WOFF2'
    VF = 'VF'


class Sort(Enum):
    SORT_UNDEFINED = 'SORT_UNDEFINED'
    ALPHA = 'ALPHA'
    DATE = 'DATE'
    POPULARITY = 'POPULARITY'
    STYLE = 'STYLE'
    TRENDING = 'TRENDING'


class FieldXgafv(Enum):
    field_1 = '1'
    field_2 = '2'


class Alt(Enum):
    json = 'json'
    media = 'media'
    proto = 'proto'


class Capability(RootModel[List[CapabilityEnum]]):
    root: List[CapabilityEnum]


class Family(RootModel[List[str]]):
    root: List[str]
